from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from storage_framework.models import Clone, Host, RaidGroup, ReplicationSession, Snapshot, Volume, Zone


class StorageArrayAdapter(ABC):
    """Normalized contract implemented by every vendor or simulator backend."""

    @abstractmethod
    def health(self) -> dict[str, Any]: ...
    @abstractmethod
    def reset(self) -> None: ...
    @abstractmethod
    def create_raid_group(self, name: str, level: str, disks: list[str], stripe_kib: int) -> RaidGroup: ...
    @abstractmethod
    def get_raid_group(self, resource_id: str) -> RaidGroup: ...
    @abstractmethod
    def delete_raid_group(self, resource_id: str) -> None: ...
    @abstractmethod
    def create_volume(self, name: str, size_gib: int, pool: str, raid_group_id: str | None = None) -> Volume: ...
    @abstractmethod
    def get_volume(self, resource_id: str) -> Volume: ...
    @abstractmethod
    def delete_volume(self, resource_id: str) -> None: ...
    @abstractmethod
    def write_pattern(self, volume_id: str, pattern: str) -> str: ...
    @abstractmethod
    def create_replication(self, source_volume_id: str, target_array: str, mode: str, rpo_seconds: int) -> ReplicationSession: ...
    @abstractmethod
    def get_replication(self, resource_id: str) -> ReplicationSession: ...
    @abstractmethod
    def sync_replication(self, resource_id: str) -> ReplicationSession: ...
    @abstractmethod
    def failover_replication(self, resource_id: str) -> ReplicationSession: ...
    @abstractmethod
    def failback_replication(self, resource_id: str) -> ReplicationSession: ...
    @abstractmethod
    def delete_replication(self, resource_id: str) -> None: ...
    @abstractmethod
    def create_snapshot(self, volume_id: str, name: str) -> Snapshot: ...
    @abstractmethod
    def get_snapshot(self, resource_id: str) -> Snapshot: ...
    @abstractmethod
    def restore_snapshot(self, snapshot_id: str) -> Volume: ...
    @abstractmethod
    def delete_snapshot(self, resource_id: str) -> None: ...
    @abstractmethod
    def create_clone(self, source_id: str, source_type: str, name: str) -> Clone: ...
    @abstractmethod
    def get_clone(self, resource_id: str) -> Clone: ...
    @abstractmethod
    def split_clone(self, resource_id: str) -> Clone: ...
    @abstractmethod
    def delete_clone(self, resource_id: str) -> None: ...
    @abstractmethod
    def create_zone(self, name: str, initiators: list[str], targets: list[str]) -> Zone: ...
    @abstractmethod
    def activate_zone(self, resource_id: str) -> Zone: ...
    @abstractmethod
    def get_zone(self, resource_id: str) -> Zone: ...
    @abstractmethod
    def delete_zone(self, resource_id: str) -> None: ...
    @abstractmethod
    def create_host(self, name: str, initiators: list[str]) -> Host: ...
    @abstractmethod
    def map_volume(self, volume_id: str, host_id: str, path_count: int = 2) -> Host: ...
    @abstractmethod
    def get_host(self, resource_id: str) -> Host: ...
    @abstractmethod
    def set_path_state(self, host_id: str, path_id: str, state: str) -> Host: ...
    @abstractmethod
    def unmap_volume(self, volume_id: str, host_id: str) -> None: ...
    @abstractmethod
    def delete_host(self, resource_id: str) -> None: ...
    @abstractmethod
    def set_metadata(self, resource_type: str, resource_id: str, values: dict[str, str]) -> dict[str, str]: ...
    @abstractmethod
    def get_metadata(self, resource_type: str, resource_id: str) -> dict[str, str]: ...
    @abstractmethod
    def delete_metadata_key(self, resource_type: str, resource_id: str, key: str) -> dict[str, str]: ...
